package com.anabivirtual.story.editor;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * Main window frame of the ANABIVIRTUAL story editor.
 * @author pedro
 */
public class MainJFrame
	extends javax.swing.JFrame
{

	/** Creates new form MainJFrame */
	public MainJFrame() {
		initComponents();
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {
      java.awt.GridBagConstraints gridBagConstraints;

      javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
      javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
      createDataBaseButton = new javax.swing.JButton();
      editDatabaseButton = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle(Utilities.getString("MainFrameTitle")); // NOI18N

      jLabel1.setText(Utilities.getString("MainFrameHeader")); // NOI18N
      getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

      jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(Utilities.getString("WhatToDo"))); // NOI18N
      jPanel1.setLayout(new java.awt.GridBagLayout());

      createDataBaseButton.setText(Utilities.getString("CreateDatabase")); // NOI18N
      createDataBaseButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            createDataBaseButtonActionPerformed(evt);
         }
      });
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
      gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
      jPanel1.add(createDataBaseButton, gridBagConstraints);

      editDatabaseButton.setText(Utilities.getString("EditDatabase")); // NOI18N
      editDatabaseButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            editDatabaseButtonActionPerformed(evt);
         }
      });
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
      gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
      jPanel1.add(editDatabaseButton, gridBagConstraints);

      getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void createDataBaseButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_createDataBaseButtonActionPerformed
   {//GEN-HEADEREND:event_createDataBaseButtonActionPerformed
      int returnValue;
		JFileChooser fc = new JFileChooser ();
		fc.setDialogType (JFileChooser.CUSTOM_DIALOG);
		fc.setDialogTitle (Utilities.getString ("SelectDatabaseToCreateTitle"));
		fc.setFileSelectionMode (JFileChooser.FILES_ONLY);
		fc.setMultiSelectionEnabled (false);
		returnValue = fc.showDialog (this, Utilities.getString ("Select"));
		if (returnValue == 0) {
			File f = fc.getSelectedFile ();
			if (!f.exists ()
			     || (
			          f.exists () && f.isFile ()
			          && JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog (this,
			               Utilities.getString ("FileAlreadyExists"),
			               Utilities.getString ("WarningTitle"),
								JOptionPane.YES_NO_OPTION,
			               JOptionPane.WARNING_MESSAGE))) {
				System.out.format ("MISSING: show the database editor for file %s\n", f.getAbsolutePath ());
			}
		}
   }//GEN-LAST:event_createDataBaseButtonActionPerformed

   private void editDatabaseButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_editDatabaseButtonActionPerformed
   {//GEN-HEADEREND:event_editDatabaseButtonActionPerformed
		int returnValue;
		JFileChooser fc = new JFileChooser ();
		fc.setDialogType (JFileChooser.CUSTOM_DIALOG);
		fc.setDialogTitle (Utilities.getString ("SelectDatabaseToEditTitle"));
		fc.setFileSelectionMode (JFileChooser.FILES_ONLY);
		fc.setMultiSelectionEnabled (false);
		returnValue = fc.showOpenDialog (this);
		if (returnValue == 0) {
			File f = fc.getSelectedFile ();
			if (f.exists () && f.isFile ()) {
				System.out.format ("MISSING: show the database editor for file %s\n", f.getAbsolutePath ());
			}
		}
   }//GEN-LAST:event_editDatabaseButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainJFrame().setVisible(true);
			}
		});
	}

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton createDataBaseButton;
   private javax.swing.JButton editDatabaseButton;
   // End of variables declaration//GEN-END:variables

}
